application: esoteric-cider-119511
runtime: go
api_version: go1
version:  r1

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html
  secure: always

- url: /css
  static_dir: css/
  secure: always

- url: /js
  static_dir: js/
  secure: always

- url: /go/.*
  script: _go_app
  secure: always
