runtime: go
api_version: go1
version:  r110
automatic_scaling:
        max_concurrent_requests: 80
        max_idle_instances: 1
        min_pending_latency: 500ms

inbound_services:
- channel_presence

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html
  login: admin
  secure: always

- url: /historyview.html
  static_files: templates/historyview.html
  upload: templates/historyview.html
  login: admin
  secure: always

- url: /mainview.html
  static_files: templates/mainview.html
  upload: templates/mainview.html
  login: admin
  secure: always

- url: /editdialog.html
  static_files: templates/editdialog.html
  upload: templates/editdialog.html
  login: admin
  secure: always

- url: /css
  static_dir: css/
  login: admin
  secure: always

- url: /js
  static_dir: js/
  login: admin
  secure: always

- url: /go/.*
  script: _go_app
  login: admin
  secure: always

- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: static/images/favicon\.ico

- url: /_ah/channel/connected/
  login: admin
  secure: always
  script: _go_app

- url: /_ah/channel/disconnected/
  script: _go_app
  login: admin
  secure: always