runtime: go
api_version: go1

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html

- url: /css
  static_dir: css/

- url: /js
  static_dir: js/

- url: /go/.*
  script: _go_app
