runtime: go
api_version: go1
version:  r115
automatic_scaling:
        max_concurrent_requests: 80
        max_idle_instances: 1
        min_pending_latency: 500ms

default_expiration: "1d"

inbound_services:
- warmup

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html
  # login: admin
  secure: always

- url: /historyview.html
  static_files: templates/historyview.html
  upload: templates/historyview.html
  # login: admin
  secure: always

- url: /mainview.html
  static_files: templates/mainview.html
  upload: templates/mainview.html
  # login: admin
  secure: always

- url: /editdialog.html
  static_files: templates/editdialog.html
  upload: templates/editdialog.html
  # login: admin
  secure: always

- url: /public
  static_dir: public/
  # login: admin
  secure: always

- url: /go/.*
  script: _go_app
  # login: admin
  secure: always

- url: /cron/summarizedaily
  script: _go_app
  # login: admin
  secure: always

- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: static/images/favicon\.ico

- url: /img/ic_menu_24px\.svg
  static_files: img/ic_menu_24px.svg
  upload: img/ic_menu_24px.svg

- url: /_ah/warmup
  script: _go_app
  login: admin
